# Dev Config

server:
  port: 8585
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:oracle
    username: system
    password: 123
    driver-class-name: oracle.jdbc.OracleDriver
  jackson:
    serialization:
      fail-on-empty-beans: false

# Example configuration for Oracle
#spring:
#  jpa:
#    database: oracle
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle12cDialect
#    hibernate:
#      ddl-auto: update

# Logging
logging:
  pattern:
    console: "%d [%level] %c{1.} [%t] %m%n"
  file:
    name: emp.log
    pattern: "%d [%level] %c{1.} [%t] %m%n"
